project:
  type: website
  output-dir: docs

website:
  title: "Ian R. McDonald"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - movie.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true



